version: "3.4"

services:
  pessoapi:
    container_name: pessoa_api
    image: pessoa_api
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    build: 
      context: .
      dockerfile: Dockerfile